#!/usr/bin/env bash

# Script to cross-compile Box2D as a Windows DLL using MinGW-w64 on Linux

cd box2d;
read -p "Ready Lets Go" READYLETSGO;

# Exit immediately if a command exits with a non-zero status.
set -e

LINKER_SCRIPT_PATH_RELATIVE_TO_SOURCE_ROOT="box2d.map"

# --- Configuration ---
# Adjust these paths and names if necessary
BOX2D_SOURCE_DIR=".." # Assuming this script is run from within a 'scripts' subdir of box2d_sys, and box2d source is one level up
BUILD_DIR="build_mingw_dll"
TARGET_ARCH="x86_64" # For 64-bit DLL
#TARGET_ARCH="i686"   # For 32-bit DLL (use i686-w64-mingw32-gcc)

if [ "$TARGET_ARCH" == "x86_64" ]; then
    C_COMPILER="x86_64-w64-mingw32-gcc"
    CXX_COMPILER="x86_64-w64-mingw32-g++"
else
    C_COMPILER="i686-w64-mingw32-gcc"
    CXX_COMPILER="i686-w64-mingw32-g++"
fi
# ... (compiler checks as before) ...

# --- Build Steps ---
echo "Removing old build directory: $BUILD_DIR"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
# Important: CMake commands should be run from within the build directory
cd "$BUILD_DIR"

echo "Configuring CMake for MinGW DLL build..."
cmake \
    -S "$BOX2D_SOURCE_DIR" \
    -DCMAKE_SYSTEM_NAME=Windows \
    -DCMAKE_C_COMPILER="$C_COMPILER" \
    -DCMAKE_CXX_COMPILER="$CXX_COMPILER" \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DBOX2D_BUILD_UNIT_TESTS=OFF \
    -DBOX2D_BUILD_TESTBED=OFF \
    -DBOX2D_BUILD_DOCS=OFF \
    -DBOX2D_SAMPLES=OFF \
    -DBOX2D_BENCHMARKS=OFF \
    -DBOX2D_PROFILE=OFF \
    -DBOX2D_VALIDATE=ON \
    -DENKITS_BUILD_EXAMPLES=OFF \
    -DBOX2D_ENABLE_SIMD=ON \
    .


# --- PREPROCESS STEP ---
echo "---------------------------------------------------------------------"
echo "Preprocessing world.c to examine B2_API macro expansion..."
echo "---------------------------------------------------------------------"
# Construct the include paths string from CMake's generated response file
# This assumes the response file for includes is generated for the 'box2d' target
# The path might be src/CMakeFiles/box2d.dir/includes_C.rsp
# If this file isn't there yet because no build has happened, this part might be tricky.
# Let's try to get includes from CMAKE_CURRENT_SOURCE_DIR and CMAKE_CURRENT_BINARY_DIR
# which are used in target_include_directories.

# A more robust way might be to capture CFLAGS from a dummy build or use compile_commands.json
# For now, let's try with known include paths.
# The crucial includes for box2d itself are:
# -I../box2d/include (relative to this script if run from box2d_sys root and BUILD_DIR is ../build_box2d_mingw_dll)
# -I./include (relative to the build directory if box2d_config.h is generated there)
# From your log, it seems `includes_C.rsp` is the key. We need to ensure it's generated by the configure step.
# If the configure step writes CMakeFiles/box2d.dir/flags.make, that might contain C_DEFINES and C_INCLUDES.

# Let's try to get CMake to tell us the compile flags for one file
# This might require a slight restructuring or running a partial build if CMake doesn't write this out early.

# Alternative: Manually list known critical include paths
# This is less ideal but can work for a focused test.
# The include path for "box2d/box2d.h" is ${BOX2D_SOURCE_DIR}/include
# The include path for generated headers (if any, like a config.h) would be ${CMAKE_CURRENT_BINARY_DIR} (which is pwd here)
PREPROCESS_INCLUDES="-I${BOX2D_SOURCE_DIR}/include -I."

echo "Running: $C_COMPILER -DBOX2D_ENABLE_SIMD -DBOX2D_VALIDATE -Dbox2d_EXPORTS ${PREPROCESS_INCLUDES} -E ${BOX2D_SOURCE_DIR}/src/world.c > world.i"
$C_COMPILER -DBOX2D_ENABLE_SIMD -DBOX2D_VALIDATE -Dbox2d_EXPORTS ${PREPROCESS_INCLUDES} -E "${BOX2D_SOURCE_DIR}/src/world.c" > world.i

echo "Preprocessed output written to $(pwd)/world.i"
echo "Please inspect world.i and search for 'b2World_Create' or other B2_API functions."
echo "Check what B2_API expanded to."
echo "Pausing for inspection. Press Enter to continue with full build, or Ctrl+C to abort."
read -p "Inspect world.i now. Press Enter to continue build..."
# --- END PREPROCESS STEP ---

echo "Building Box2D DLL..."
cmake --build . --config Release 

echo "Build complete."
DLL_OUTPUT_PATH="src/libbox2d.dll"
IMPORT_LIB_OUTPUT_PATH="src/libbox2d.dll.a"

if [ -f "$DLL_OUTPUT_PATH" ] && [ -f "$IMPORT_LIB_OUTPUT_PATH" ]; then
    echo "Main Box2D DLL is at: $(pwd)/${DLL_OUTPUT_PATH}"
    echo "Main Box2D Import library is at: $(pwd)/${IMPORT_LIB_OUTPUT_PATH}"
    
    TARGET_PREBUILT_DIR_SCRIPT_RELATIVE_PATH="../prebuilt_mingw_libs" # Path relative to the script's dir if script is in box2d_sys root
    # Assuming this script (build_dll.sh) is in the root of box2d_sys:
    # And BUILD_DIR is also relative to box2d_sys root e.g., build_box2d_mingw_dll (not ../build_box2d_mingw_dll)
    # If script is in box2d_sys/ and BUILD_DIR is box2d_sys/build_box2d_mingw_dll then:
    # TARGET_PREBUILT_DIR="./prebuilt_mingw_libs" 
    # cp "${DLL_OUTPUT_PATH}" "${TARGET_PREBUILT_DIR}/box2d.dll"
    # cp "${IMPORT_LIB_OUTPUT_PATH}" "${TARGET_PREBUILT_DIR}/libbox2d.dll.a"
    # echo "Copied artifacts to $TARGET_PREBUILT_DIR (assuming script is in box2d_sys root)"
    echo "MANUALLY COPY: cp $(pwd)/${DLL_OUTPUT_PATH} ../prebuilt_mingw_libs/box2d.dll"
    echo "MANUALLY COPY: cp $(pwd)/${IMPORT_LIB_OUTPUT_PATH} ../prebuilt_mingw_libs/libbox2d.dll.a"

else
    echo "Error: Expected DLL artifacts not found in $(pwd)/src/ !"
fi

cd .. # Return to the script's original directory or box2d_sys root